version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.0.2

workflows:
  maven_test:
    jobs:
      - maven/test
      - coverage:
          requires:
            - maven/test
          steps:
            - codecov/upload:
                file: { { coverage_report_filepath } }



