version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: mvn install
      - run: mvn test
      - run: "mvn cobertura:cobertura"
      - run: "bash <(curl -s https://codecov.io/bash)"
      - save_cache:
          paths:
            - ~/.m2
          key: dependencies