version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  version: 2
  test-qa:
    jobs:
      - tests

job_defaults: &job_defaults
  docker:
    - image: circleci/maven@0.0.12

jobs:
  tests:
    <<: *job_defaults
    steps:
      - maven/test
      - run: mvn cobertura:cobertura
      - run: bash <(curl -s https://codecov.io/bash)



